# Repository settings set via https://github.com/probot/settings

repository:
  has_issues: true
  has_wiki: true
  has_projects: true
  has_downloads: false

labels:
  - name: bug
    color: d73a4a
  - name: documentation
    color: 0075ca
  - name: duplicate
    color: cfd3d7
  - name: enhancement
    color: a2eeef
  - name: good first issue
    color: 7057ff
  - name: help wanted
    color: 008672
  - name: idea/discussion
    color: 87899D
  - name: invalid
    color: e4e669
  - name: question
    color: d876e3
  - name: todo
    color: EBB602
  - name: WIP
    color: 61D569
  - name: wontfix
    color: ffffff

# Not implemented by probot/settings, implemented by .github/scripts/deploy
branch_protection:
  restrictions: null
  enforce_admins: false
  required_status_checks:
    strict: true
    contexts:
      - "continuous-integration/travis-ci"
  required_pull_request_reviews:
    require_code_owner_reviews: true
