#!/bin/sh

set -e

if [ "$1" = "cicd" ]; then
  install_list="gcc make cmake python3 python3-dev python3-setuptools \
                python-setuptools zlib1g zlib1g-dev ruby ruby-dev ruby-full fontconfig yarn \
                graphviz graphviz-dev graphviz-doc libgdbm-dev libgdbm-compat-dev \
                fonts-linuxlibertine texlive-lang-french texlive-latex-base \
                texlive-latex-recommended python-pil-doc python-pil-dbg python-renderpm-dbg \
                python-egenix-mxtexttools python-reportlab-doc python-setuptools-doc \
                sgml-base-doc debhelper python-seqdiag python-blockdiag python-actdiag \
                python-nwdiag python3-graphv"

  echo "Installing/Updating Dependencies"
  for dependency in $install_list ; do
    if ! dpkg-query -W "$dependency" > /dev/null 2>&1; then
      echo "Installing \"$dependency\""
      # sudo apt-get install $dependency -y
    else
      echo "Updating   \"$dependency\""
      # sudo apt-get upgrade $dependency -y
    fi
  done
exit 0
else
  # Install site dependencies
  python3 -m pip --no-cache install blockdiag seqdiag actdiag nwdiag graphviz
  gem install bundler
  gem install rubocop
  gem install ffi --platform=ruby
  gem install kramdown-parser-gfm
  gem install http_parser.rb
  gem install jekyll

  # Install requirements for jekyll to build the website
  bundle install
fi
